# Generated by Django 4.0 on 2021-12-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_new_users_newusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewUsers',
            new_name='NewUser',
        ),
    ]
